@echo off
REM deploy.bat - Local FTP deployment script for PhotoSite
REM Usage: Just run this file when you want to deploy changes to your live website
REM It will:
REM   1. Pull latest code from GitHub
REM   2. Sync changed files to your FTP server using WinSCP

setlocal enabledelayedexpansion

echo.
echo =====================================
echo PhotoSite - Local FTP Deployment
echo =====================================
echo.

REM Step 1: Pull latest from GitHub
echo [1/3] Pulling latest changes from GitHub...
echo.

git pull origin main

if !errorlevel! neq 0 (
    echo.
    echo ❌ ERROR: Failed to pull from GitHub
    echo Make sure you're in the PhotoSite directory and have git installed
    pause
    exit /b 1
)

echo.
echo ✅ GitHub pull complete
echo.

REM Step 2: Sync to FTP using WinSCP
echo [2/3] Syncing files to FTP server...
echo.
echo Note: This uses WinSCP for secure FTP synchronization
echo If WinSCP is not installed, download from: https://winscp.net/eng/download.php
echo.

REM Create WinSCP script file
echo # WinSCP Synchronization Script > sync-script.txt
echo # Auto-generated by deploy.bat >> sync-script.txt
echo. >> sync-script.txt
echo open "ftp://%%FTP_USERNAME%%:%%FTP_PASSWORD%%@%%FTP_HOST%%" >> sync-script.txt
echo. >> sync-script.txt
echo # Exclude unnecessary files >> sync-script.txt
echo option exclude *.md.*,*.py.*,.git\*,.gitignore >> sync-script.txt
echo. >> sync-script.txt
echo # Synchronize local to remote >> sync-script.txt
echo synchronize remote -delete >> sync-script.txt
echo. >> sync-script.txt
echo exit >> sync-script.txt

REM Check if WinSCP is installed
if exist "C:\Program Files (x86)\WinSCP\WinSCP.com" (
    echo Using WinSCP from: C:\Program Files (x86)\WinSCP
    "C:\Program Files (x86)\WinSCP\WinSCP.com" /console /script=sync-script.txt /log="sync.log"
) else if exist "C:\Program Files\WinSCP\WinSCP.com" (
    echo Using WinSCP from: C:\Program Files\WinSCP
    "C:\Program Files\WinSCP\WinSCP.com" /console /script=sync-script.txt /log="sync.log"
) else (
    echo.
    echo ❌ ERROR: WinSCP not found!
    echo.
    echo WinSCP is required for FTP synchronization.
    echo Download it here: https://winscp.net/eng/download.php
    echo.
    echo After installing, run this script again.
    echo.
    pause
    exit /b 1
)

if !errorlevel! neq 0 (
    echo.
    echo ❌ ERROR: WinSCP sync failed
    echo Check your FTP credentials and server settings
    echo WinSCP log saved to: sync.log
    pause
    exit /b 1
)

echo.
echo ✅ FTP sync complete
echo.

REM Step 3: Cleanup
echo [3/3] Cleaning up temporary files...
if exist sync-script.txt del sync-script.txt
if exist sync.log del sync.log

echo.
echo =====================================
echo ✅ DEPLOYMENT SUCCESSFUL!
echo =====================================
echo.
echo Your changes are now live on your website!
echo.

pause
